name: forwantofanail
channels:
  - conda-forge
dependencies:
  - python=3.11
  - sqlalchemy
  - h3-py
  - fastapi
  - uvicorn
  - pytest
  - alembic
  - psycopg
  - pillow
  - rasterio
  - pyshp
  - ffmpeg
  - pip
  - pip:
      - "mcp>=2,<3"
